# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14inzDPR2jqxsWnwc8CcUNryApcgnQh4_
"""

import streamlit as st
import numpy as np
import tensorflow as tf
import cv2
from streamlit_drawable_canvas import st_canvas

# 1. Load the model
@st.cache_resource
def load_model():
    return tf.keras.models.load_model('mnist_model.h5')

model = load_model()

st.title("Handwriting Digit Recognizer")
st.markdown("Draw a digit (0-9) inside the box below:")

# 2. Create the Canvas (Black background, white pen)
canvas_result = st_canvas(
    stroke_width=15,
    stroke_color="#FFFFFF",
    background_color="#000000",
    height=150,
    width=150,
    drawing_mode="freedraw",
    key="canvas",
)

# 3. Predict when button is clicked
if st.button('Predict'):
    if canvas_result.image_data is not None:
        # Convert drawn image to grayscale and resize to 28x28
        img = cv2.resize(canvas_result.image_data.astype('uint8'), (28, 28))
        img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

        # Normalize (0 to 1) and reshape for model
        img = img / 255.0
        img = img.reshape(1, 28, 28, 1)

        # Predict
        prediction = model.predict(img)
        digit = np.argmax(prediction)

        st.success(f"## Predicted Digit: {digit}")
        st.bar_chart(prediction[0])
    else:
        st.warning("Please draw something first!")