# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14inzDPR2jqxsWnwc8CcUNryApcgnQh4_
"""

import streamlit as st
import numpy as np
import tensorflow as tf
import cv2
from streamlit_drawable_canvas import st_canvas

# 1. Load the model securely (Fixes 'Optimizer' errors)
@st.cache_resource
def load_model():
    # compile=False avoids version mismatch errors between Colab and Streamlit
    return tf.keras.models.load_model('mnist_model.h5', compile=False)

model = load_model()

st.title("Handwriting Digit Recognizer")
st.markdown("Draw a digit (0-9) inside the box below:")

# 2. Create the Canvas
canvas_result = st_canvas(
    stroke_width=15,
    stroke_color="#FFFFFF", # White pen
    background_color="#000000", # Black background
    height=150,
    width=150,
    drawing_mode="freedraw",
    key="canvas",
)

if st.button('Predict'):
    if canvas_result.image_data is not None:
        # A. Basic Preprocessing
        # Convert to grayscale and resize to 28x28
        img = cv2.resize(canvas_result.image_data.astype('uint8'), (28, 28))
        img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        img = img / 255.0 # Normalize 0-1

        # B. "Smart" Shape Detection
        # This block checks what shape YOUR model wants and reshapes the image automatically
        input_shape = model.input_shape

        # Sometimes input_shape includes the batch dimension (None), sometimes it doesn't.
        # We ensure we are looking at the actual data dimensions.
        if input_shape[0] is None:
            expected_dims = len(input_shape) - 1
        else:
            expected_dims = len(input_shape)

        if expected_dims == 3:
            # Model expects 3D image: (28, 28, 1)
            img = img.reshape(1, 28, 28, 1)
        elif expected_dims == 1:
            # Model expects Flattened list: (784,)
            img = img.reshape(1, 784)
        else:
            # Fallback for simple 2D input: (28, 28)
            img = img.reshape(1, 28, 28)

        # C. Predict
        try:
            prediction = model.predict(img)
            digit = np.argmax(prediction)
            st.success(f"## Predicted Digit: {digit}")
            st.bar_chart(prediction[0])
        except Exception as e:
            st.error(f"An error occurred: {e}")

    else:
        st.warning("Please draw something first!")